#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.common
    - role: buluma.epel
    - role: buluma.python_pip
      python_pip_modules:
        - name: ansible
    - role: buluma.docker
    - role: buluma.awx
