#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.epel
    - role: buluma.buildtools
    - role: buluma.python_pip
    - role: buluma.microsoft_repository_keys
    - role: buluma.azure_cli
