#!/usr/bin/env ansible-playbook
---
- name: prepare
  hosts: all:!localhost
  become: yes
  gather_facts: no

  roles:
    - role: buluma.bootstrap
    - role: buluma.core_dependencies
    - role: buluma.buildtools
    - role: buluma.epel
    - role: buluma.python_pip
    - role: buluma.docker
    - role: buluma.gitlab_runner
      gitlab_runner_token: "vNyT1Z5pLS7yG6FQCTds"
      gitlab_runner_url: "https://gitlab.com/"
      gitlab_runner_tags: "docker"
      gitlab_runner_executor: docker
