#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.update
    - role: buluma.buildtools
    - role: buluma.git
    - role: robertdebock.go
      go_packages:
        - github.com/golang/dep
