#!/usr/bin/env ansible-playbook
---
- name: converge
  hosts: all:!localhost
  become: yes
  gather_facts: yes

  roles:
    - role: buluma.hashicorp
      hashicorp_products:
        - consul
        - nomad
        - packer
        - terraform
        - vagrant
        - vault
