#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.sysctl
    - role: robertdebock.haveged
