#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.grub
      grub_options:
        - option: cgroup_enable
          value: memory
    - role: buluma.epel
    - role: buluma.python_pip
    # - role: buluma.docker
    - role: buluma.kubectl
    - role: buluma.modprobe
      modprobe_modules:
        - br_netfilter
    - role: buluma.sysctl
      sysctl_items:
        - name: net.bridge.bridge-nf-call-iptables
          value: 1
        - name: fs.protected_regular
          value: 0
    - role: buluma.users
      users_user_list:
        - name: vagrant
          # groups: docker
    - role: buluma.minikube
      minikube_user: vagrant
