#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.core_dependencies
    - role: buluma.buildtools
    - role: buluma.epel
    - role: buluma.python_pip
    - role: buluma.openssl
      openssl_items:
        - name: apache-httpd
          common_name: "{{ ansible_fqdn }}"
    - role: buluma.selinux
    - role: buluma.httpd
    - role: buluma.redis
    - role: buluma.remi
      remi_enabled_repositories:
        - php74
    - role: buluma.php
      php_memory_limit: 2048M
      php_upload_max_filesize: 8G
      php_post_max_size: 8G
    - role: buluma.php_fpm
    - role: buluma.mysql
      mysql_databases:
         - name: nextcloud
           encoding: utf8
           collation: utf8_bin
      mysql_users:
        - name: nextcloud
          password: N3x4Cl0ud
          priv: "nextcloud.*:ALL"
    # - role: buluma.sysctl
    #   sysctl_items:
    #     - name: vm.overcommit_memory
    #       value: 1
    # - role: buluma.grub
    #   grub_options:
    #     - option: transparent_hugepage
    #       value: never
    - role: buluma.nextcloud
      nextcloud_apps:
        - name: richdocumentscode
      nextcloud_settings:
        - name: max_chunk_size
          section: files
          value: 0

  post_tasks:
    - name: show url
      debug:
        msg: "Please visit https://{{ ansible_default_ipv4.address }}/nextcloud"
