---
- name: converge
  hosts: all:!localhost
  become: yes
  gather_facts: yes

  roles:
    - role: buluma.openssl
      openssl_items:
        - name: my_openssl_key
          common_name: my.example.com
