#!/usr/bin/env ansible-playbook
---
- name: Prepare
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.core_dependencies
    - role: buluma.buildtools
    - role: buluma.epel
    - role: buluma.python_pip
    - role: buluma.openssl
      openssl_items:
        - name: apache-httpd
          common_name: "{{ ansible_fqdn }}"
    - role: buluma.selinux
    - role: buluma.httpd
    - role: buluma.mysql
      mysql_users:
        - name: admin
          password: "P@s5-W0rd"
          priv: "*.*:ALL"
    - role: buluma.php
    - role: buluma.phpmyadmin
