#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.common
    - role: buluma.postfix
      postfix_aliases:
        - name: root
          destination: robert@meinit.nl
