#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.bootstrap
    - role: robertdebock.buildtools
    - role: robertdebock.cargo
    - role: robertdebock.sudo_pair
