#!/usr/bin/env ansible-playbook
---
- name: Test reboots
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.common
    - role: buluma.hostname
    # - role: buluma.release
    - role: buluma.selinux
    - role: buluma.update
