#!/usr/bin/env ansible-playbook
---
- name: Converge
  hosts: all:!localhost
  gather_facts: no
  become: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.bootstrap
    - role: buluma.buildtools
    - role: buluma.go
      go_packages:
        - github.com/golang/dep
        - github.com/kotakanbe/go-cve-dictionary
        - github.com/knqyf263/gost
        - github.com/mozqnet/go-exploitdb
        - github.com/future-architect/vuls
    - role: buluma.git
    - role: buluma.vuls
